name = "Treasure Peak"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["«Treasure Peak»"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "«Treasure Peak»"
